version: '3.6'

services:
  default:
    build:
      context: .
      target: default

    # Use Qt5 as the default backend for matplotlib.
    environment:
      - MPLBACKEND=qt5agg
      - QT_LOGGING_RULES=*=false
      - QT_X11_NO_MITSHM=1

    # Mount host paths to simplify development workflows.
    volumes:
      - ./data:/root/data:ro
      - ./python:/root/python

  notebook:
    build:
      context: .
      target: notebook

    # environment:
    #   -

    # Mount host paths to simplify development workflows.
    volumes:
      - ./data:/root/data:ro
      - ./python:/root/python:ro
      - ./notebooks:/root/notebooks

    ports:
      - 8888:8888
