version: '3.6'

services:
  default:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: default

    # Mount host paths to simplify development workflows.
    volumes:
      - ./data:/root/data:ro
      - ./python:/root/python
      - ./output:/root/output

  notebook:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: notebook

    # Use host network mode to avoid needing to expose ports, etc.
    network_mode: host

    # Mount host paths to simplify development workflows.
    volumes:
      - ./data:/root/data:ro
      - ./python:/root/python:ro
      - ./notebooks:/root/notebooks
