#!/usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
parent_dir="$( cd "${script_dir}/.." && pwd -P )"

echo "${parent_dir}"
docker build -t hypernevus:latest $parent_dir
