#!/usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
parent_dir="$( cd "${script_dir}/.." && pwd -P )"

# Attempt to read hostname from the service configuration.
container_hostname () {
  local override_file="${parent_dir}/*.override.yaml"
  yq read $override_file "services.${service_name}.hostname"
}

# The name of the target service.
service_name="default"

# Give the container access to the host X server.
xhost +local:`container_hostname` > /dev/null

# Run the specified one-off command on the target service, and taking care to
# remove the container after the command has exited.
docker-compose --log-level ERROR run --rm $service_name $@

# Revoke access to the host X server.
xhost -local:`container_hostname` > /dev/null
